name: Reusable rust checks

on:
  workflow_call:

jobs:
  rust-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: [test, clippy, fmt]

    steps:
      - run: sudo apt-get update

      - run: sudo apt-get install -y protobuf-compiler

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rustfmt
          override: true

      - name: Cache Rust
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            **/target
          key: >
            rust-${{ runner.os }}-nightly-
            ${{
              hashFiles(
                'Cargo.lock',
                '**/Cargo.lock',
                '**/build.rs'
              )
            }}
          restore-keys: |
            rust-${{ runner.os }}-

      - name: Run check
        run: |
          if [ "${{ matrix.check }}" = "test" ]; then
            cargo test --all --all-features --locked --jobs $(nproc)
          elif [ "${{ matrix.check }}" = "clippy" ]; then
            cargo clippy --locked --all-targets --all-features -- -D warnings
          elif [ "${{ matrix.check }}" = "fmt" ]; then
            cargo metadata --locked --format-version 1 --no-deps > /tmp/cargo-metadata.json
            cargo fmt --all -- --check
          fi
