name: Reusable NX publish

on:
  workflow_call:
    inputs:
      appId:
        required: true
        type: string
      isProd:
        required: false
        type: boolean
    secrets:
      appSecret:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.appSecret }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          name: ci-builder

      - name: Install Buildpack CLI
        run: |
          (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.36.2/pack-v0.36.2-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)

      - uses: actions/checkout@v5
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0
          filter: tree:0

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Yarn cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Check if nextjs is needed
        id: nextjs
        run: |
          if test -f "next.config.ts"; then
            echo "needed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Nextjs cache
        uses: actions/cache@v4
        if: steps.nextjs.outputs.needed == 'true'
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Check if Cargo is needed
        id: cargo
        run: |
          if test -f "Cargo.toml"; then
            echo "needed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Cargo cache
        uses: actions/cache@v4
        if: steps.cargo.outputs.needed == 'true'
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - run: yarn install --inline-builds

      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ github.ref_name }}

      - name: Publish stage docker image
        if: ${{ inputs.isProd == false }}
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          export TAG_PREFIX=stage-
          export TAG_SUFFIX=stage
          export TAG_POLICY=ctx-hash-timestamp
          export DATE=$(date +%s)
          yarn nx affected -t publish --configuration production --outputStyle=stream --parallel=0

      - name: Release
        if: ${{ inputs.isProd == true }}
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          yarn nx release

      - name: Commit changes
        uses: planetscale/ghcommit-action@v0.2.20
        if: ${{ inputs.isProd == true }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          repo: ${{ github.repository }}
          branch: ${{ github.ref_name }}
          commit_message: 'chore(common): update versions'
          file_pattern: '*.json *.md *.toml *.lock'

      - name: Publish prod docker image
        if: ${{ inputs.isProd == true }}
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TAG_PREFIX=prod-
          export TAG_SUFFIX=latest
          export TAG_POLICY=hash-timestamp
          export DATE=$(date +%s)
          yarn nx affected -t publish --configuration production --outputStyle=stream --parallel=0
